"""pwd

Revision ID: 7679d40ba9ba
Revises: 7db9c69a5510
Create Date: 2021-09-25 19:29:13.059087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7679d40ba9ba'
down_revision = '7db9c69a5510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cd_users_username_key', 'cd_users', schema='auth', type_='unique')
    op.create_index(op.f('ix_auth_cd_users_username'), 'cd_users', ['username'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_cd_users_username'), table_name='cd_users', schema='auth')
    op.create_unique_constraint('cd_users_username_key', 'cd_users', ['username'], schema='auth')
    # ### end Alembic commands ###
