"""password_added

Revision ID: 89387d3e46ca
Revises: 7679d40ba9ba
Create Date: 2021-09-25 19:59:24.944577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89387d3e46ca'
down_revision = '7679d40ba9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('c_username', sa.String(length=500), nullable=False), schema='auth')
    op.add_column('cd_users', sa.Column('c_password', sa.String(length=500), nullable=False), schema='auth')
    op.drop_index('ix_auth_cd_users_username', table_name='cd_users', schema='auth')
    op.create_index(op.f('ix_auth_cd_users_c_username'), 'cd_users', ['c_username'], unique=True, schema='auth')
    op.drop_column('cd_users', 'username', schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('username', sa.VARCHAR(length=500), autoincrement=False, nullable=False), schema='auth')
    op.drop_index(op.f('ix_auth_cd_users_c_username'), table_name='cd_users', schema='auth')
    op.create_index('ix_auth_cd_users_username', 'cd_users', ['username'], unique=False, schema='auth')
    op.drop_column('cd_users', 'c_password', schema='auth')
    op.drop_column('cd_users', 'c_username', schema='auth')
    # ### end Alembic commands ###
