"""init

Revision ID: 5ff0465c50bc
Revises: 
Create Date: 2021-09-20 10:23:51.884188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ff0465c50bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_entities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='идентификатор'),
    sa.PrimaryKeyConstraint('id'),
    schema='common',
    comment='сущности'
    )
    op.create_table('cd_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='идентификатор'),
    sa.Column('c_username', sa.String(length=500), nullable=False, comment='логин'),
    sa.ForeignKeyConstraint(['id'], ['common.cd_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin',
    comment='пользователи'
    )
    op.create_index(op.f('ix_admin_cd_users_c_username'), 'cd_users', ['c_username'], unique=True, schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_cd_users_c_username'), table_name='cd_users', schema='admin')
    op.drop_table('cd_users', schema='admin')
    op.drop_table('cd_entities', schema='common')
    # ### end Alembic commands ###
