"""init

Revision ID: 66d91d0c7df4
Revises: 
Create Date: 2021-09-19 18:10:00.327230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66d91d0c7df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_entities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='идентификатор'),
    sa.PrimaryKeyConstraint('id'),
    schema='common',
    comment='сущности'
    )
    op.create_table('cd_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='идетификатор'),
    sa.Column('c_username', sa.String(length=500), nullable=False, comment='имя пользователя'),
    sa.Column('c_password', sa.String(length=500), nullable=False, comment='пароль'),
    sa.Column('c_lastname', sa.String(length=500), nullable=False, comment='фамилия'),
    sa.Column('c_firstname', sa.String(length=500), nullable=False, comment='имя'),
    sa.ForeignKeyConstraint(['id'], ['common.cd_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='пользователи'
    )
    op.create_index(op.f('ix_auth_cd_users_c_username'), 'cd_users', ['c_username'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_cd_users_c_username'), table_name='cd_users', schema='auth')
    op.drop_table('cd_users', schema='auth')
    op.drop_table('cd_entities', schema='common')
    # ### end Alembic commands ###
