"""user_fio

Revision ID: 8ac4d2d2c3f6
Revises: fbb19ffdd782
Create Date: 2021-09-21 15:36:57.128045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac4d2d2c3f6'
down_revision = 'fbb19ffdd782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('c_lastname', sa.String(length=500), nullable=False, comment='фамилия'), schema='admin')
    op.add_column('cd_users', sa.Column('c_firstname', sa.String(length=500), nullable=False, comment='имя'), schema='admin')
    op.add_column('cd_users', sa.Column('c_middlename', sa.String(length=500), nullable=True, comment='отчество'), schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_users', 'c_middlename', schema='admin')
    op.drop_column('cd_users', 'c_firstname', schema='admin')
    op.drop_column('cd_users', 'c_lastname', schema='admin')
    # ### end Alembic commands ###
