"""token

Revision ID: aa407a0787a4
Revises: 89387d3e46ca
Create Date: 2021-09-27 10:58:30.586914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa407a0787a4'
down_revision = '89387d3e46ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('c_refresh_token', sa.String(length=500), nullable=True), schema='auth')
    op.alter_column('cd_users', 'id',
               existing_type=postgresql.UUID(),
               comment='идентификатор',
               existing_nullable=False,
               schema='auth')
    op.alter_column('cd_users', 'c_username',
               existing_type=sa.VARCHAR(length=500),
               comment='логин',
               existing_nullable=False,
               schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cd_users', 'c_username',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='логин',
               existing_nullable=False,
               schema='auth')
    op.alter_column('cd_users', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='идентификатор',
               existing_nullable=False,
               schema='auth')
    op.drop_column('cd_users', 'c_refresh_token', schema='auth')
    # ### end Alembic commands ###
