"""comments

Revision ID: c9c1bc96e739
Revises: aa407a0787a4
Create Date: 2021-09-27 11:24:57.682968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c1bc96e739'
down_revision = 'aa407a0787a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cd_users', 'c_password',
               existing_type=sa.VARCHAR(length=500),
               comment='пароль',
               existing_nullable=False,
               schema='auth')
    op.alter_column('cd_users', 'c_refresh_token',
               existing_type=sa.VARCHAR(length=500),
               comment='токен',
               existing_nullable=True,
               schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cd_users', 'c_refresh_token',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='токен',
               existing_nullable=True,
               schema='auth')
    op.alter_column('cd_users', 'c_password',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='пароль',
               existing_nullable=False,
               schema='auth')
    # ### end Alembic commands ###
