"""token field added

Revision ID: defbe88ba247
Revises: 8ac4d2d2c3f6
Create Date: 2021-09-25 13:08:34.922885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defbe88ba247'
down_revision = '8ac4d2d2c3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('c_refresh_token', sa.String(length=500), nullable=True, comment='рефреш токен'), schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_users', 'c_refresh_token', schema='admin')
    # ### end Alembic commands ###
