"""pwd

Revision ID: fbb19ffdd782
Revises: 5ff0465c50bc
Create Date: 2021-09-20 10:27:18.006140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb19ffdd782'
down_revision = '5ff0465c50bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_users', sa.Column('c_password', sa.String(length=500), nullable=False, comment='пароль'), schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_users', 'c_password', schema='admin')
    # ### end Alembic commands ###
